# pylint: disable=missing-docstring,redefined-builtin,wrong-import-position
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

# -- Project information -----------------------------------------------------

from datetime import date
import os.path
import sys

parent_dir = os.path.dirname(os.path.dirname(__file__))
# make sure that the chital source directory is first on the list
sys.path.insert(0, os.path.join(parent_dir, 'src'))

project = 'Roll With It'

copyright = date.today().strftime('%Y, Brendan McGloin')
author = 'Brendan McGloin'

# The short X.Y version
version = '0.0.1'
# The full version, including alpha/beta/rc tags
release = '0.0.1'

highlight_language = 'python'
add_module_names = False

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'chios.bolditalic',
    'humanfriendly.sphinx',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.autosummary',
    'sphinx.ext.ifconfig',
    'sphinx.ext.intersphinx',
    'sphinx_git',
    'sphinxcontrib.spelling',
    'sphinx_issues',
]

default_role = 'any'
primary_domain = 'py'
# keep_warnings = True
modindex_common_prefix = [
    'rollit.',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'style_external_links': True,
    # 'vcs_pageview_mode': 'view',
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Roll With It'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Roll With It.tex', 'Roll With It Documentation', 'Brendan McGloin', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, 'roll-with-it', 'Roll With It Documentation', [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Roll With It', 'Roll With It Documentation', author, 'Roll With It',
     'A dice roller interface and library built in python.', 'Miscellaneous'),
]

# -- Extension configuration -------------------------------------------------
# Stuff for autodoc
# autoclass_content = 'both'
autodoc_inherit_docstrings = False
autodoc_member_order = 'groupwise'
autodoc_mock_imports = []
autodoc_default_options = {
    'member-order': 'groupwise',
    'exclude-members': '__weakref__',
}

autosectionlabel_prefix_document = True

# Stuff for issues
#TODO May need to change
issues_uri = 'https://github.com/russels-crockpot/roll-with-it/issues{issue}'
issues_pr = 'https://github.com/russels-crockpot/roll-with-it/pulls/{pr}'
issues_user_uri = 'https://github.com/{user}'

spelling_lang = 'en_US'
spelling_show_suggestions = True
